ShopEcommerce/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using ShopEcommerce.Models;
using ShopEcommerce.ViewModels;

namespace ShopEcommerce.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pieRepository;
        private readonly ICategoryRepository categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            this.pieRepository = pieRepository;
            this.categoryRepository = categoryRepository;
        }

        //public IActionResult List()
        //{
        //    //ViewBag.CurrentCategory = "Cheese cakes";
        //    //return View(pieRepository.AllPies);
        //    PieListViewModel piesListViewModel = new PieListViewModel(pieRepository.AllPies, "All pies");
        //    return View(piesListViewModel);
        //}
        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string? currentCategory;
            if(string.IsNullOrEmpty(category))
            {
                pies = pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All Pies";
            }
            else
            {
                pies = pieRepository.AllPies.Where(p => p.Category.CategoryName == category).OrderBy(p => p.PieId);
                currentCategory = categoryRepository.AllCategories.First(c=> c.CategoryName == category)?.CategoryName;
            }

            return View(new PieListViewModel(pies,currentCategory));
        }



        public IActionResult Details(int id)
        {
            var pie = pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();  
            return View(pie);
        }


        public IActionResult Search()
        {
            return View();
        }
    }
}

ShopEcommerce/Pages/Shared/_pageLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Pie Shop</title>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans' rel='stylesheet' type='text/css'>

    <script src="~/lib/jquery/jquery.js"></script>

    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <link href="~/site.css" rel="stylesheet" />
    <script src="~/jquery-validate/jquery.validate.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <base href="/" />
</head>
<body>
    <div>
        <div class="container">

            <header>
                <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                     aria-label="Bethany's Pie Shop navigation header">
                    <div class="container-xl">
                        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                            <img src="images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47" class="d-inline-block align-top mb-2 mt-1"
                                 alt="Bethany's Pie Shop Logo">
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarCollapse">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                <vc:category-menu></vc:category-menu>
                                <li class="nav-item">
                                    <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact</a>
                                </li>
                                @*   <li class="nav-item">
                                <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                                </li>
                                <li class="nav-item">
                                <a asp-controller="Pie" asp-action="List" class="nav-link">Pies</a>
                                </li> *@
                            </ul>
                            <vc:shopping-cart-summary></vc:shopping-cart-summary>
                        </div>
                    </div>
                </nav>
            </header>

            @RenderBody()
        </div>


    </div>


</body>
</html>